version: '3.8'

services:
  mongo-db:
    image: mongo:7.0.5
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: &{MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017